<a href="https://colab.research.google.com/github/sanha-hwang/EEG_project/blob/workspace/Project_EEG_DL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<H1>Project : EEG signal 분석 </H1>

[datasetLink](https://www.kaggle.com/wanghaohan/confused-eeg)

1. EEG 신호란 electroencephalography의 약자이며 '뇌전도'라고 번역된다.  전극을 통해 뇌의 전기적인 활동을 기록하는 전기생리학적 측정방법을 말한다. 뇌의 활동은 뇌파라는 전기신호를 방출하게 되고 EEG을 통해 뇌파의 스펙트럼 밀도를 분석하게 된다.    

2. 데이터는 10명의 대학생을 대상으로 여러 카테고리별로 10개씩 총 20개의 동영상을 시청하면서 전두엽의 활동을 측정하여, 혼란스러울 때의 뇌파상태와 평온할 때의 뇌파상태를 측정하였습니다. 동영상에는 혼란스럽지않을 기초대수학 또는 기하학을 소개하는 온라인 교육영상이 있으며, 반대로 익숙치 않으면 혼란스러울 양자역학, 줄기세포 연구 등 과 같은 주제의 교육영상이 있습니다. 동영상 길이는 약 2분이며, 영상을 조금 더 혼란스럽게 만들기 위해 주제 중간에 2분클립을 잘랐습니다.


3. 학생들은 전두엽의 활동을 측정하는 단일 무선채널의 mindset을 착용하였으며, Mindset은 이마에 있는 전극과 귀에 각각 접촉하는 두 개의 전극 사이의 전압을 측정하였습니다.    

4. 각 학생들은 세션이 끝난 후, 자신의 혼란 정도를 1-7의 척도로 평가하였으며, 1은 최저, 7은 최고 레벨입니다. 혼란정도는 정규화되어 labeling 되었다.

5. column 분석
  - 'SubjectID': 피실험자 ID
  - ' age': 피실험자 나이
  - ' ethnicity' :피실험자 민족
  - ' gender': 피실험자 성별
  -  'VideoID': 시청한 비디오영상번호
  - 'Attention': 집중도 수치
  - 'Mediation': 평온함 수치
  - 'Raw': EEG 장비로 측정하여 나온 수치
  - 'Delta': Raw를 가공하여 나온 1-3Hz Power Spectrum
  - 'Theta': Raw를 가공하여 나온 4-7Hz Power Spectrum
  - 'Alpha1': Raw를 가공하여 나온 Lower 8-11Hz Power Spectrum
  - 'Alpha2': Raw를 가공하여 나온 High 8-11Hz Power Spectrum
  - 'Beta1': Raw를 가공하여 나온 Lower 12-29Hz Power Spectrum
  - 'Beta2': Raw를 가공하여 나온 High 12-29Hz Power Spectrum
  - 'Gamma1': Raw를 가공하여 나온 Lower 30-100Hz Power Spectrum
  - 'Gamma2': Raw를 가공하여 나온 High 30-100Hz Power Spectrum
  - 'predefinedlabel': Subject의 expected confusion level
  - 'user-definedlabeln': Subject의 actually confusion level

6. Brain wave 정리   
  - Delta wave: 깊은 수면을 취할 때, 약하게 깨어 있을 때 혹은 무의식 일 때의 뇌파, 잠잘 때 장기기억, 해마가 작용할 때나오는 뇌파    
부족한 경우- 불면증,세타파가 나오게 되면 깊은 수면을 취할 수 없음, 과할 경우 - 늘 뇌가 피곤해 있고 무기력해질 우려가 있음

  - Theta wave:  꾸벅꾸벅 조는 상태, - 여명상태, 내면의식, 기억력, 창의력, 명상, 퍼포먼스 ,신비하고 미묘한  것이어서 실험자들이 연구하기 어려웟음, 세타파에 있는 동안, 의식을 유지하기 어렵기 때문   
부족한 경우- 창의력부족, 예민, 과할 경우- 안정성이 없음,늘 에너지가 없어보임

  - Alpha wave : 눈을 감고 편안한 상태, 집중하지 않은 상태일 때, 뇌파활동은 느려짐, 아주 편안하게 이완되고 정신적으로 집중되지 않는 상태, 알파상태에는 두뇌의 '중립' 또는 한가한 상태처럼 보이나, 건강하고 스트레스에 지배받지 않는 사람들은 많은 양의 알파파를 만들어냄,
알파파의 결핍: 불안, 스트레스, 뇌 활성 저하, 과도한 의식활동(산만함)에 노출, 이완능력, 에너지, 기억력, 창의력 강화훈련 필요
SM알파파: 알파파 끝부분, 생리적으로 이완 상태, 의식적으로 각성된 상태, 면역력이나 스트레스에 대한 저항능력
각성능력을 보여주는 지표, 두뇌활동에 가장 중심적 뇌파
오감에서 들어오는 외부의 감각센서와 운동능력    
부족한 경우-긴장과 불안에 매일 수 있음, 과한경우-급한 것이 없음, 일처리에 맺고 끊는 맛이 없음

  - Beta wave: 일반적으로 외부세계에 꺠어 있을 때, 눈을 뜨고 집중하는 상태, 구체적이고특별한 문제를 다루고 있을 때, 상대방이 어떻게 나올지 집중하는 상태
특히 14-40, 두뇌에서 가장 지배적이고 강력하게 활동, 민첩성, 각성 ,집중, 인식력과 관련, 과도할 경우 불안 유발   
부족한 경우-매사에 의욕이 없음, 과한 경우- 산만한 활동, 행동의 자제가 되지 않아 함부로 행동







In [ ]:
pip install eli5

     |████████████████████████████████| 106 kB 5.1 MB/s 


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

EEG_data = pd.read_csv("/content/drive/MyDrive/EEG_data.csv") # EEG 데이터 불러오기
person_info = pd.read_csv("/content/drive/MyDrive/demographic_info.csv") #실험군 데이터

In [ ]:
# data정리
EEG_data[['SubjectID','VideoID', 'user-definedlabeln']] = EEG_data[['SubjectID','VideoID', 'user-definedlabeln']].astype(int)
person_info.rename(columns={'subject ID':'SubjectID'}, inplace= True)
data = person_info.merge(EEG_data,on ='SubjectID')
data.rename(columns={' age':'age'}, inplace= True)
data.rename(columns={' ethnicity':'ethnicity'}, inplace= True)
data.rename(columns={' gender':'gender'}, inplace= True)
data.rename(columns={'user-definedlabeln':'Label'}, inplace= True)


In [ ]:
data.head()

In [ ]:
data.dtypes

In [ ]:
data.isnull().sum()

In [ ]:
data.duplicated().sum()

In [ ]:
data.columns

Index(['SubjectID', 'age', 'ethnicity', 'gender', 'VideoID', 'Attention',
       'Mediation', 'Raw', 'Delta', 'Theta', 'Alpha1', 'Alpha2', 'Beta1',
       'Beta2', 'Gamma1', 'Gamma2', 'predefinedlabel', 'Label'],
      dtype='object')

In [ ]:
# EDA
data.drop(columns=['predefinedlabel', 'ethnicity', 'VideoID'], inplace=True)
data = data.replace({'gender' :{'M': 1, 'F': 0}})

In [ ]:
data.head()

SubjectID  age  gender  Attention  ...     Beta2   Gamma1   Gamma2  Label
0          0   25       1       56.0  ...   45097.0  33228.0   8293.0      0
1          0   25       1       40.0  ...    3687.0   5293.0   2740.0      0
2          0   25       1       47.0  ...  130536.0  57243.0  25354.0      0
3          0   25       1       47.0  ...   62462.0  49960.0  33932.0      0
4          0   25       1       44.0  ...   99603.0  44790.0  29749.0      0

[5 rows x 15 columns]

In [ ]:
data.shape

(12811, 15)

In [ ]:
#혹시 모르니 깊은 복사로 진행
y = data['Label'].copy()
X = data.drop('Label', axis=1).copy()

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV




In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score, f1_score, confusion_matrix
def eval(test, pred= None, proba=None):
  confusion = confusion_matrix(test, pred)
  accuracy = accuracy_score(test, pred)
  precision = precision_score(test,pred)
  recall = recall_score(test, pred)
  roc_auc = roc_auc_score(test, proba)
  F1 = f1_score(test, pred)

  print('오차행렬')
  print(confusion)

  print('정확도: {0:.4f}, 정밀도: {1:.4f}, 재현율: {2:.4f}, F1: {3:.4f}, AUC: {4:.4f}'.format(accuracy, precision, recall, F1, roc_auc))




In [ ]:
# scaler = StandardScaler()
# X = scaler.fit_transform(X)


In [ ]:
X.shape

(12811, 15)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state= 42)

In [ ]:
#base

y_base1 = [1] * len(y_val)


confusion = confusion_matrix(y_val, y_base1)
accuracy = accuracy_score(y_val, y_base1)
precision = precision_score(y_val, y_base1)
recall = recall_score(y_val, y_base1)
F1 = f1_score(y_val, y_base1)
roc_auc = roc_auc_score(y_val, y_base1)

print('오차행렬')
print(confusion)

print('정확도: {0}, 정밀도: {1}, 재현율: {2}, F1: {3}, auc:{4}'.format(accuracy, precision, recall, F1, roc_auc))

오차행렬
[[   0 1023]
 [   0 1027]]
정확도: 0.5009756097560976, 정밀도: 0.5009756097560976, 재현율: 1.0, F1: 0.6675333116672083, auc:0.5


In [ ]:
# 여러 ML 사용해보기- > 트리 계열은 과적합이 나옴 그나마 랜덤포레스트 모델, XGBoost, LGBM 이 70퍼센트 나옴

In [ ]:
from sklearn.ensemble import RandomForestClassifier

forest_model = RandomForestClassifier()
forest_model.fit(X_train, y_train)
y_pred = forest_model.predict(X_val)
y_proba = forest_model.predict_proba(X_val)[:,1]

eval(y_val, y_pred, y_proba)

오차행렬
[[728 295]
 [276 751]]
정확도: 0.7215, 정밀도: 0.7180, 재현율: 0.7313, F1: 0.7246, AUC: 0.7891


In [ ]:
forest_param ={   'n_estimators':[10,50,100,200] ,
                  'criterion': ['gini', 'entropy'], 
                  'max_depth':[5, 10, 20, 30, 50, None]
                }

grid_search_forest = GridSearchCV(forest_model, forest_param, cv =10, scoring='roc_auc')
grid_search_forest.fit(X_train, y_train)

In [ ]:
grid_search_forest.best_estimator_

In [ ]:
grid_search_forest.best_params_

In [ ]:
grid_search_forest.best_score_

In [ ]:
#fine tunning forest
opforest_model = RandomForestClassifier(criterion= 'entropy', max_depth= 30, n_estimators= 200)
opforest_model.fit(X_train, y_train)
y_pred = opforest_model.predict(X_val)
y_proba = opforest_model.predict_proba(X_val)[:,1]

eval(y_val, y_pred, y_proba)

# forest_model : 0.7185, 정밀도: 0.7103, 재현율: 0.7400, F1: 0.7248, AUC: 0.7908 -> critical하게 변하지 않았다.

오차행렬
[[699 324]
 [269 758]]
정확도: 0.7107, 정밀도: 0.7006, 재현율: 0.7381, F1: 0.7188, AUC: 0.7916


In [ ]:
# permuter 정의
import eli5
from eli5.sklearn import PermutationImportance

permuter = PermutationImportance(
    forest_model, # model
    scoring='accuracy', # metric
    n_iter=5, # 다른 random seed를 사용하여 5번 반복
    random_state=2
)

# 실제로 fit 의미보다는 스코어를 다시 계산하는 작업입니다
permuter.fit(X_val, y_val);

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.feature_selection.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.feature_selection. Anything that cannot be imported from sklearn.feature_selection is now part of the private API.
  warnings.warn(message, FutureWarning)


In [ ]:
feature_names = X_val.columns.tolist()
pd.Series(permuter.feature_importances_, feature_names).sort_values()

gender       0.009463
Raw          0.011902
Alpha1       0.012000
Beta1        0.012390
Theta        0.013463
Alpha2       0.016585
Beta2        0.026927
Mediation    0.028000
Delta        0.036683
age          0.040878
Gamma1       0.043512
SubjectID    0.053366
Gamma2       0.063805
Attention    0.074049
dtype: float64

In [ ]:
from xgboost import XGBClassifier

XG_model = XGBClassifier()
XG_model.fit(X_train, y_train)

y_pred = XG_model.predict(X_val)
y_proba = XG_model.predict_proba(X_val)[:,1]

eval(y_val, y_pred, y_proba)

오차행렬
[[665 358]
 [289 738]]
정확도: 0.6844, 정밀도: 0.6734, 재현율: 0.7186, F1: 0.6952, AUC: 0.7562


In [ ]:
XGB_params ={'n_estimators':[10,50,100,200] ,
            'criterion': ['gini', 'entropy'], 
            'max_depth':[5, 10, 20, 30, 50, None],
            'learning_rate' : [0.05 , 0.1, 0.2],
            'subsample' : [0.7]
                }

grid_search_XGB = GridSearchCV(XG_model, XGB_params, cv =5, scoring='roc_auc')
grid_search_XGB.fit(X_train, y_train)

In [ ]:
grid_search_XGB.best_estimator_

In [ ]:
grid_search_XGB.best_params_

In [ ]:
grid_search_XGB.best_score_

In [ ]:
opXG_model = XGBClassifier(criterion = 'gini', learning_rate = 0.05, max_depth = 50, n_estimators = 200, subsample = 0.7)
opXG_model.fit(X_train, y_train)

y_pred = opXG_model.predict(X_val)
y_proba = opXG_model.predict_proba(X_val)[:,1]

eval(y_val, y_pred, y_proba)
# 정확도: 0.6844, 정밀도: 0.6734, 재현율: 0.7186, F1: 0.6952, AUC: 0.7562 -> 전반적으로 개선이 됨

오차행렬
[[700 323]
 [278 749]]
정확도: 0.7068, 정밀도: 0.6987, 재현율: 0.7293, F1: 0.7137, AUC: 0.7883


In [ ]:
from lightgbm import LGBMClassifier

light_model = LGBMClassifier()
light_model.fit(X_train, y_train)
y_pred = light_model.predict(X_val)
y_proba = light_model.predict_proba(X_val)[:,1]

eval(y_val, y_pred, y_proba)

오차행렬
[[691 332]
 [290 737]]
정확도: 0.6966, 정밀도: 0.6894, 재현율: 0.7176, F1: 0.7032, AUC: 0.7827


In [ ]:
light_params ={'n_estimators':[10,50,100,200],
               'criterion': ['gini', 'entropy'], 
               'max_depth':[5, 10, 20, 30, 50, None],
               'learning_rate' : [0.05 , 0.1, 0.2]
                }

grid_search_light = GridSearchCV(light_model, light_params, cv =5, scoring='roc_auc')
grid_search_light.fit(X_train, y_train)

In [ ]:
grid_search_light.best_estimator_

In [ ]:
grid_search_light.best_params_

In [ ]:
grid_search_light.best_score_

In [ ]:
oplight_model = LGBMClassifier(criterion = 'gini', learning_rate = 0.05, max_depth = 20, n_estimators = 200)
oplight_model.fit(X_train, y_train)
y_pred = oplight_model.predict(X_val)
y_proba = oplight_model.predict_proba(X_val)[:,1]

eval(y_val, y_pred, y_proba)

#정확도: 0.6966, 정밀도: 0.6894, 재현율: 0.7176, F1: 0.7032, AUC: 0.7827 -> 크리티컬한 변화는 없었다.

오차행렬
[[704 319]
 [293 734]]
정확도: 0.7015, 정밀도: 0.6971, 재현율: 0.7147, F1: 0.7058, AUC: 0.7824


RandomForest, XGBoost, LGBM 3가지 머신러닝 모델에 대해 그리드서치 후 최적의 파라미터를 조정하였다. 
딥러닝 모델또한 적용해보고 결과를 비교 후 피쳐엔지니어링을 조금 더 생각해볼 것